-- 1. Remove obsolete columns from risk_management_plan
ALTER TABLE public.risk_management_plan 
  DROP COLUMN IF EXISTS "Impact",
  DROP COLUMN IF EXISTS "Appetite";

-- 2. Add new columns for Rubrics and Scope
ALTER TABLE public.risk_management_plan
  ADD COLUMN IF NOT EXISTS "risk_scope" text DEFAULT 'Institution',
  ADD COLUMN IF NOT EXISTS "programs" text,
  ADD COLUMN IF NOT EXISTS "rubric_green" text,
  ADD COLUMN IF NOT EXISTS "rubric_yellow" text,
  ADD COLUMN IF NOT EXISTS "rubric_orange" text,
  ADD COLUMN IF NOT EXISTS "rubric_red" text;

-- 3. Create risk_values table for data entry
CREATE TABLE IF NOT EXISTS public.risk_values (
    id bigint generated by default as identity primary key,
    risk_id bigint references public.risk_management_plan(id) on delete cascade,
    academic_year text,
    program_name text,
    value numeric,
    created_at timestamp with time zone default now(),
    UNIQUE(risk_id, academic_year, program_name)
);

ALTER TABLE public.risk_values ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable read access for all on risk_values" ON public.risk_values;
CREATE POLICY "Enable read access for all on risk_values" ON public.risk_values FOR SELECT USING (true);
DROP POLICY IF EXISTS "Enable insert access for authenticated" ON public.risk_values;
CREATE POLICY "Enable insert access for authenticated" ON public.risk_values FOR INSERT WITH CHECK (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable update access for authenticated" ON public.risk_values;
CREATE POLICY "Enable update access for authenticated" ON public.risk_values FOR UPDATE USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable delete access for authenticated" ON public.risk_values;
CREATE POLICY "Enable delete access for authenticated" ON public.risk_values FOR DELETE USING (auth.role() = 'authenticated');

-- 4. Drop old KRI tables
DROP TABLE IF EXISTS public.risk_kri_values;
DROP TABLE IF EXISTS public.kri_rubrics;
DROP TABLE IF EXISTS public.risk_kris;
