-- OBF KPI Management Schema

-- 1. KPI Categories
CREATE TABLE IF NOT EXISTS public.obf_categories (
    id bigint generated by default as identity primary key,
    value text NOT NULL,
    label text NOT NULL,
    sort_order integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.obf_categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access on obf_categories" ON public.obf_categories FOR ALL USING (true) WITH CHECK (true);

-- Insert default categories
INSERT INTO public.obf_categories (value, label, sort_order) VALUES
('C01', 'Academic Performance', 1),
('C02', 'Student Success', 2),
('C03', 'Research & Innovation', 3),
('C04', 'Financial Sustainability', 4),
('C05', 'Operational Excellence', 5)
ON CONFLICT DO NOTHING;

-- 2. OBF KPIs Master Table
CREATE TABLE IF NOT EXISTS public.obf_kpis (
    id bigint generated by default as identity primary key,
    kpi_no text UNIQUE,
    title text NOT NULL,
    category text,
    description text,
    numerator_label text,
    denominator_label text,
    unit text,
    rubric_green text,
    rubric_yellow text,
    rubric_orange text,
    rubric_red text,
    created_at timestamp with time zone DEFAULT now(),
    reporter_email text
);

ALTER TABLE public.obf_kpis ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access on obf_kpis" ON public.obf_kpis FOR ALL USING (true) WITH CHECK (true);

-- 3. OBF KPI Values (per Academic Year / Institution or Program)
CREATE TABLE IF NOT EXISTS public.obf_kpi_values (
    id bigint generated by default as identity primary key,
    kpi_id bigint REFERENCES public.obf_kpis(id) ON DELETE CASCADE,
    academic_year text NOT NULL,
    program_name text NOT NULL DEFAULT 'Institution',
    numerator numeric,
    denominator numeric,
    value numeric,
    created_at timestamp with time zone DEFAULT now(),
    UNIQUE(kpi_id, academic_year, program_name)
);

ALTER TABLE public.obf_kpi_values ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access on obf_kpi_values" ON public.obf_kpi_values FOR ALL USING (true) WITH CHECK (true);

-- 4. OBF KPI Year Mapping (Active KPIs per Year)
CREATE TABLE IF NOT EXISTS public.obf_kpi_year_mapping (
    id bigint generated by default as identity primary key,
    kpi_id bigint REFERENCES public.obf_kpis(id) ON DELETE CASCADE,
    academic_year text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    UNIQUE(kpi_id, academic_year)
);

ALTER TABLE public.obf_kpi_year_mapping ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access on obf_kpi_year_mapping" ON public.obf_kpi_year_mapping FOR ALL USING (true) WITH CHECK (true);
