-- ============================================================
-- Supabase Migration: KRI Fields + Scope Decoupling
-- Run this in Supabase SQL Editor
-- Date: 2026-05-02
-- ============================================================

-- 1. Add KRI fields to risk_management_plan table
--    KRI_Title: short text for the Key Risk Indicator name
--    KRI_Calculation: rich text (HTML) for how the KRI is calculated
ALTER TABLE public.risk_management_plan
  ADD COLUMN IF NOT EXISTS "KRI_Title" text,
  ADD COLUMN IF NOT EXISTS "KRI_Calculation" text;

-- 2. Scope is no longer set on the risk record.
--    It is now per-value (risk_values.program_name = 'Institution' or a program name).
--    The risk_scope and programs columns are kept for backward compatibility
--    but are no longer written to by the UI.
--    NO ACTION NEEDED — existing data is preserved.

-- 3. Ensure the programs table exists (used by the risk values scope dropdown).
--    This table should already exist from OrgManager, but just in case:
CREATE TABLE IF NOT EXISTS public.programs (
  id bigint generated by default as identity primary key,
  name text NOT NULL,
  college_id bigint references public.colleges(id) on delete set null,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.programs ENABLE ROW LEVEL SECURITY;

-- Allow read for all authenticated users
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'programs' AND policyname = 'Enable read access for all on programs'
  ) THEN
    CREATE POLICY "Enable read access for all on programs"
      ON public.programs FOR SELECT USING (true);
  END IF;
END $$;

-- 4. Verify role_permissions table has the required columns (should already exist)
--    The UI now uses can_view + can_edit as a combined permission level:
--      No Access:   row deleted or both false
--      View Only:   can_view=true, can_edit=false
--      View & Edit: can_view=true, can_edit=true
--    NO SCHEMA CHANGES NEEDED — existing columns are reused.

-- Done! After running this, refresh your app.
